### ISSUE TITLE
Exception when no kubeconfig can be found

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rd#116]
On a new machine, running `npm run dev`, I get this error message in the console:

```
(node:15202) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, watch
    at FSWatcher.start (internal/fs/watchers.js:169:26)
    at Object.watch (fs.js:1343:11)
    at new Tray (/Users/ericp/workspace/rancher/desktop/app/background.js:3916:8)
    at _callee2$ (/Users/ericp/workspace/rancher/desktop/app/background.js:34665:18)
    at tryCatch (/Users/ericp/workspace/rancher/desktop/app/background.js:32119:40)
    at Generator.invoke [as _invoke] (/Users/ericp/workspace/rancher/desktop/app/background.js:32349:22)
    at Generator.next (/Users/ericp/workspace/rancher/desktop/app/background.js:32174:21)
    at asyncGeneratorStep (/Users/ericp/workspace/rancher/desktop/app/background.js:64:24)
    at _next (/Users/ericp/workspace/rancher/desktop/app/background.js:86:9)
    at /Users/ericp/workspace/rancher/desktop/app/background.js:93:7
(node:15202) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15202) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mook-as** [comment]
Fixed in #120.
