### ISSUE TITLE
Kubernetes fails to run on Windows upgrade

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rd#288]
Have Rancher Desktop working on windows. Get an installer for a newer version of RD and run it. After install, Rancher Desktop doesn't come up. Instead you get an error like...

<img width="851" alt="Screen Shot 2021-05-13 at 3 18 44 PM" src="https://user-images.githubusercontent.com/62991/118175876-abc7df80-b3fe-11eb-9c57-fb110b673fb9.png">

**Comment by mook-as** [comment]
I can reproduce, just quit and started RD again (without reinstalling):
<details><summary>IP 172.24.224.182</summary>

```
[Window Title]
Error

[Main Instruction]
Error Starting Kubernetes

[Content]
There was an unknown error starting Kubernetes: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: 172.24.224.182 is not in the cert's list: 10.43.0.1, 127.0.0.1, 172.24.232.192

[OK]
```
</details>

This is the IP address of the WSL VM.

Looking for that address in the K3s logs, I see:
```
I0514 17:54:34.591810      18 server.go:659] external host was not specified, using 172.24.224.182
time="2021-05-14T17:54:37.654545400Z" level=info msg="To join node to cluster: k3s agent -s https://172.24.224.182:6443 -t ${NODE_TOKEN}"
W0514 17:54:51.280703      18 lease.go:233] Resetting endpoints for master service "kubernetes" to [172.24.224.182]
time="2021-05-14T17:55:37.224750900Z" level=info msg="Connecting to proxy" url="wss://172.24.224.182:6443/v1-k3s/connect"
time="2021-05-14T17:55:37.230937800Z" level=info msg="Updating TLS secret for k3s-serving (count: 8): map[listener.cattle.io/cn-10.43.0.1:10.43.0.1 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.24.224.182:172.24.224.182 listener.cattle.io/cn-172.24.232.192:172.24.232.192 listener.cattle.io/cn-kubernetes:kubernetes listener.cattle.io/cn-kubernetes.default:kubernetes.default listener.cattle.io/cn-kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local listener.cattle.io/cn-localhost:localhost listener.cattle.io/fingerprint:SHA1=294E8F00D916D6AF7DA1BE006C1629CC37893E31]"
time="2021-05-14T17:55:37.245157900Z" level=info msg="Active TLS secret k3s-serving (ver=620) (count 8): map[listener.cattle.io/cn-10.43.0.1:10.43.0.1 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.24.224.182:172.24.224.182 listener.cattle.io/cn-172.24.232.192:172.24.232.192 listener.cattle.io/cn-kubernetes:kubernetes listener.cattle.io/cn-kubernetes.default:kubernetes.default listener.cattle.io/cn-kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local listener.cattle.io/cn-localhost:localhost listener.cattle.io/fingerprint:SHA1=294E8F00D916D6AF7DA1BE006C1629CC37893E31]"
I0514 17:55:37.454161      18 flannel.go:105] Using interface with name eth0 and address 172.24.224.182
time="2021-05-14T17:55:58.978622700Z" level=info msg="Updated coredns node hosts entry [172.24.224.182 desktop-6mvg5i4]"
time="2021-05-14T17:56:43.153086600Z" level=info msg="error in remotedialer server [400]: read tcp 172.24.224.182:6443->172.24.224.182:46840: i/o timeout"
time="2021-05-14T17:56:50.843184800Z" level=error msg="Remotedialer proxy error" error="read tcp 172.24.224.182:46840->172.24.224.182:6443: i/o timeout"
time="2021-05-14T17:56:56.618267000Z" level=info msg="Connecting to proxy" url="wss://172.24.224.182:6443/v1-k3s/connect"
```

Best guess is, the IP address changed in WSL? I'm not sure where the addresses in the cert came from.

**Comment by mook-as** [comment]
<details><summary>The error was logged in <tt>background.log</tt></summary>

```
Kubernetes was unable to start: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: 172.24.224.182 is not in the cert's list: 10.43.0.1, 127.0.0.1, 172.24.232.192
    at Object.checkServerIdentity (tls.js:288:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1494:27)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket._finishInit (_tls_wrap.js:927:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:697:12) {
  reason: "IP: 172.24.224.182 is not in the cert's list: 10.43.0.1, 127.0.0.1, 172.24.232.192",
  host: '172.24.224.182',
  cert: {
    subject: [Object: null prototype] { O: 'k3s', CN: 'k3s' },
    issuer: [Object: null prototype] { CN: 'k3s-server-ca@1621013987' },
    subjectaltname: 'DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc.cluster.local, DNS:localhost, IP Address:10.43.0.1, IP Address:127.0.0.1, IP Address:172.24.232.192',
    bits: 256,
    pubkey: <Buffer 04 e5 27 26 60 3b 65 ae c3 ba 40 45 d5 f2 6e 38 af ec 3f a3 39 70 36 8d fa a0 d7 d0 50 1f 34 ed 4c 06 35 89 c0 6c 62 ec 35 33 72 cc 64 e8 43 dc 0f 17 ... 15 more bytes>,
    asn1Curve: 'prime256v1',
    nistCurve: 'P-256',
    valid_from: 'May 14 17:39:47 2021 GMT',
    valid_to: 'May 14 17:39:47 2022 GMT',
    fingerprint: 'ED:71:FC:16:25:72:EF:72:75:66:30:B7:6A:87:B2:1A:1D:C7:45:00',
    fingerprint256: '65:8E:F7:D3:E9:A5:5A:FB:A2:7E:62:D7:10:05:DB:14:DD:6E:D7:64:02:F4:CE:87:CF:04:57:3D:87:07:14:C7',
    ext_key_usage: [ '1.3.6.1.5.5.7.3.1' ],
    serialNumber: '749e65a51607d882',
    raw: <Buffer 30 82 01 ec 30 82 01 93 a0 03 02 01 02 02 08 74 9e 65 a5 16 07 d8 82 30 0a 06 08 2a 86 48 ce 3d 04 03 02 30 23 31 21 30 1f 06 03 55 04 03 0c 18 6b 33 ... 446 more bytes>,
    issuerCertificate: {
      subject: [Object: null prototype],
      issuer: [Object: null prototype],
      bits: 256,
      pubkey: <Buffer 04 86 8a cc 12 8c 97 81 a5 b7 30 e2 53 78 d4 87 41 dc f3 1a e6 af b7 14 b3 f4 a2 01 06 cf b6 b3 a7 5f 51 d0 7b b1 ab 7b 3d fe e4 ee 44 f8 e5 2d be fd ... 15 more bytes>,
      asn1Curve: 'prime256v1',
      nistCurve: 'P-256',
      valid_from: 'May 14 17:39:47 2021 GMT',
      valid_to: 'May 12 17:39:47 2031 GMT',
      fingerprint: 'A1:6A:55:1D:44:6E:3B:91:E5:C3:FF:6E:FC:36:C9:88:B2:B7:7D:1C',
      fingerprint256: '22:B4:9F:10:CE:FA:A7:76:97:CF:96:75:89:6E:42:E5:07:44:D9:1A:0A:C2:A6:83:59:A5:9F:BC:EE:34:4D:16',
      serialNumber: '0',
      raw: <Buffer 30 82 01 78 30 82 01 1d a0 03 02 01 02 02 01 00 30 0a 06 08 2a 86 48 ce 3d 04 03 02 30 23 31 21 30 1f 06 03 55 04 03 0c 18 6b 33 73 2d 73 65 72 76 65 ... 330 more bytes>,
      issuerCertificate: [Circular]
    }
  },
  code: 'ERR_TLS_CERT_ALTNAME_INVALID'
}
```
</details>

I think this is supposed to come from `/var/lib/rancher/k3s/server/tls/dynamic-cert.json`, key `data['tls.crt']`:
<details><summary>Same issuer, pubkey, different validity, IP address, serial</summary>

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 4109862340247212531 (0x39092a060230d1f3)
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN=k3s-server-ca@1621013987
        Validity
            Not Before: May 14 17:39:47 2021 GMT
            Not After : May 14 17:55:37 2022 GMT
        Subject: O=k3s, CN=k3s
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub: 
                    04:e5:27:26:60:3b:65:ae:c3:ba:40:45:d5:f2:6e:
                    38:af:ec:3f:a3:39:70:36:8d:fa:a0:d7:d0:50:1f:
                    34:ed:4c:06:35:89:c0:6c:62:ec:35:33:72:cc:64:
                    e8:43:dc:0f:17:39:c7:b4:e5:f4:a4:de:2b:72:06:
                    8d:38:85:1d:3c
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Authority Key Identifier: 
                keyid:30:2F:26:71:DD:0E:99:79:49:4F:8B:82:23:02:B0:EB:86:32:15:70

            X509v3 Subject Alternative Name: 
                DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc.cluster.local, DNS:localhost, IP Address:10.43.0.1, IP Address:127.0.0.1, IP Address:172.24.224.182, IP Address:172.24.232.192
    Signature Algorithm: ecdsa-with-SHA256
         30:45:02:20:4f:28:d4:10:61:4a:1c:21:fd:e7:20:93:50:8d:
         20:f0:d4:d5:5f:d3:3c:24:53:27:e1:94:de:a2:6a:9a:87:80:
         02:21:00:d2:4a:fe:bc:8a:be:c5:5b:fc:3e:60:8f:6a:1a:76:
         76:41:56:bc:37:bf:41:b5:bf:c4:00:ad:fd:5f:18:a5:fe
```
</details>

Looking at the logs, I suspect that the IP address changed, the cert got regenerated, but we checked before the regen happened, and popped up an error immediately?
